version: "3"
volumes: 
  mysql_php_data:
services: 
  database: 
    restart: on-failure:3
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_php_data:/var/lib/mysql
    environment: 
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MTSQL_PASSWORD: 123456
  app:
    restart: on-failure:3
    build: .
    volumes: 
      - ./app/:/var/www/html/
    ports: 
      - 80:80
    environment: 
      HOST: database
      USER: root
      PASSWORD: 123456
      DATABASE: basic_crud
    depends_on: 
      - database
