version: "3"
volumes: 
  mysql_php_data:
services: 
  app:
    restart: on-failure:3
    build: .
    volumes: 
      - ./app/:/var/www/html/
    ports: 
      - 80:80
    environment: 
      HOST: database
      USER: root
      PASSWORD: 123456
      DATABASE: basic_crud
